<?php
/**
 * @file
 * Code for the tell IE use edge render engine.
 */

/**
 * Implements template_preprocess_page().
 */
function ie_edge_mode_preprocess_page(&$vars) {
  if (is_null(drupal_get_http_header('X-UA-Compatible'))) {
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'http-equiv' => 'X-UA-Compatible',
        'content' => 'IE=edge,chrome=1',
      ),
    );
    drupal_add_html_head($element, 'x_ua_compatible');
  }
}
